---
title: "Lab 3"
subtitle: ESS 330
author: Rachel Delorie
format:
  html:
    self-contained: true
---

``` {r}
# Setup
library(tidyverse)
library(flextable)
library(dplyr)
library(zoo)
library(readr)
covid_data = read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv')
rename

txt <- "2022-02-01"
class(txt)
date_example <- as.Date(txt)
class(date_example)

my.date <- as.Date("2022-02-01")
my.state <- "Colorado"
```

``` {r}
# question 2
colorado <- covid_data %>%
  filter(state == my.state) %>% 
  group_by(county) %>% 
  arrange(date) %>% 
  mutate(new_cases = cases - lag(cases), new_deaths = lag(deaths)) %>% 
  ungroup()
```

``` {r}
filter(colorado, date == my.date) %>%
  slice_max(cases, n = 5) %>%
  select(Date = date, Cases = cases, County = county) %>%
  flextable() %>%
  set_caption("Most Total Cases")

filter(colorado, date == my.date) %>% #my date and only colorado
  slice_max (cases, n = 5) %>% 
  select (Date = date, County = county, Cases = new_cases) %>% 
  flextable() %>% 
  set_caption(caption = "Most New Cases")
```

```{r}
# question 3
pop_data <- read_csv("https://www2.census.gov/programs-surveys/popest/datasets/2020-2023/counties/totals/co-est2023-alldata.csv")

pop_data <- pop_data %>%
  mutate(
    FIPS = paste0("STATE", "COUNTY")                  # Create full 5-digit FIPS code
  ) %>%
  # Step 3: Keep only columns containing "NAME" or "2021"
  select(matches("NAME|2021"), FIPS) %>%
  # Step 4: Remove state-level rows (where COUNTY == "000")
  filter("COUNTY" != "000")
```

